#ifndef COLOR_MACROS_H_INCLUDED
#define COLOR_MACROS_H_INCLUDED

#include <windows.h>

#define COLOR_00  SetConsoleTextAttribute(GetStdHandle(STD_OUTPUT_HANDLE),0 )
#define COLOR_01  SetConsoleTextAttribute(GetStdHandle(STD_OUTPUT_HANDLE),1 )
#define COLOR_02  SetConsoleTextAttribute(GetStdHandle(STD_OUTPUT_HANDLE),2 )
#define COLOR_03  SetConsoleTextAttribute(GetStdHandle(STD_OUTPUT_HANDLE),3 )
#define COLOR_04  SetConsoleTextAttribute(GetStdHandle(STD_OUTPUT_HANDLE),4 )
#define COLOR_05  SetConsoleTextAttribute(GetStdHandle(STD_OUTPUT_HANDLE),5 )
#define COLOR_06  SetConsoleTextAttribute(GetStdHandle(STD_OUTPUT_HANDLE),6 )
#define COLOR_07  SetConsoleTextAttribute(GetStdHandle(STD_OUTPUT_HANDLE),7 )
#define COLOR_08  SetConsoleTextAttribute(GetStdHandle(STD_OUTPUT_HANDLE),8 )
#define COLOR_09  SetConsoleTextAttribute(GetStdHandle(STD_OUTPUT_HANDLE),9 )
#define COLOR_0a  SetConsoleTextAttribute(GetStdHandle(STD_OUTPUT_HANDLE),10 )
#define COLOR_0b  SetConsoleTextAttribute(GetStdHandle(STD_OUTPUT_HANDLE),11 )
#define COLOR_0c  SetConsoleTextAttribute(GetStdHandle(STD_OUTPUT_HANDLE),12 )
#define COLOR_0d  SetConsoleTextAttribute(GetStdHandle(STD_OUTPUT_HANDLE),13 )
#define COLOR_0e  SetConsoleTextAttribute(GetStdHandle(STD_OUTPUT_HANDLE),14 )
#define COLOR_0f  SetConsoleTextAttribute(GetStdHandle(STD_OUTPUT_HANDLE),15 )


#endif // COLOR_MACROS_H_INCLUDED
