set lang1=IMPORTANTE# title.cfg solo funciona con opl beta superior a 1460_DB o OPL 1277 Official beta
set title-lang=title.cfg generador masivo
set lang2=este archivo por lotes generara un title.cfg para cada archivo .ELF en el directorio, luego
set lang3=ambos archivos seran copiados a una sub-carpeta
set lang4=echo por El_Isra
set lang5=Se recomienda utilizar este archivo directamente en la carpeta APPS del opl para facilitar el proceso
