
::LANG FILES
::
set lng_warning=IMPORTANT# title.cfg only works for OPL beta superior to OPL 1460_DB or OPL 1277 IFCARO
set lng0=this batch file will create a title.cfg file for every ELF file in that diretory, then it moves them to
set lng1=a new sub folder
set lng2=the file name must not contain any extra dot's (excepto la extension)
set lng3=made by El_Isra
set lng4=it's recomended to use this batch file inside the APPS folder of the opl directory
set lng5=No ELF files
::
