::LANG FILES
::
set lng_warning=IMPORTANTE# solo funciona con opl beta superior a OPL 1460_DB o OPL 1277 IFCARO
set lng0=este archivo por lotes creara un archivo title.cfg para cada archivo ELF presente en esta carpeta y movera los ELF a la
set lng1=carpeta que le corresponda
set lng2=el nombre del archivo no debe contener puntos (excepto la extension)
set lng3=creado por El_Isra
set lng4=se recomienda dejar este archivo en la carpeta APPS del opl si juega por USB o SMB para facilitar el proceso
set lng5=No hay archivos ELF
::
