set lang1=IMPORTANT# title.cfg only works with opl betas superior to 1460_DB or OPL 1277 Official beta
set title-lang=title.cfg massive generator
set lang2=this batch file will generate a title.cfg for every .ELF file in the directory, then It'll be 
set lang3=moved into a sub-folder with the same name
set lang4=the file name mustn't contain any extra dor (appart of extension)
set lang5=made by El_Isra
set lang6=it's recommended to execute this on the opl APPS folder so you dont have to move the new folders
