name: CI

on:
  push:
    branches:
      - '*'
    tags:
      - v*
  pull_request:
  repository_dispatch:
    types: [run_build]

jobs:
  build-win:
    runs-on: ubuntu-latest
    container: dockcross/windows-static-x86:latest
    steps:

    - name: Compile project
      run: |
        cd title-cfg_maker
        mkdir build
        cd build
        cmake ..
        make clean all
        ls -r
